### ISSUE TITLE
updated to 1.07 and have lost all use of homeseer

### ISSUE THREAD

**Issue by sirbooker** [jrhubott/homeseer#1]
it says i have 70 entities, and when you click on the hamburger... 1 item is missing ( reload )
all of my homeseer device now do not work
Paul

**Comment by sirbooker** [comment]
Logger: homeassistant.config_entries
Source: custom_components/homeseer/__init__.py:140
First occurred: 6:49:42 PM (1 occurrences)
Last logged: 6:49:42 PM

Error setting up entry Homeseer for homeseer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/homeseer/__init__.py", line 140, in async_setup_entry
    await homeseer.api.initialize()
  File "/usr/local/lib/python3.8/site-packages/pyhs3ng/hometroller.py", line 64, in initialize
    await self._get_devices()
  File "/usr/local/lib/python3.8/site-packages/pyhs3ng/hometroller.py", line 119, in _get_devices
    all_devices = result["Devices"]
KeyError: 'Devices'

**Comment by jrhubott** [comment]
For some reason you are not getting a valid connection to homeseer.  The return from homeseer getstatus is not returning a devices array.  Nothing in this area of the code has changed between 1.05 and 1.07.
