### ISSUE TITLE
update from 1.0.4 to 1.0.13 - startup errors

### ISSUE THREAD

**Issue by anacozero** [jrhubott/homeseer#3]
Updated to latest version from 1.0.4.

Now recieving the following error:

```
Logger: homeassistant.config_entries
Source: custom_components/homeseer/__init__.py:140
First occurred: 1:23:54 PM (1 occurrences)
Last logged: 1:23:54 PM

Error setting up entry Homeseer for homeseer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/homeseer/__init__.py", line 140, in async_setup_entry
    await homeseer.api.initialize()
  File "/usr/local/lib/python3.8/site-packages/pyhs3ng/hometroller.py", line 66, in initialize
    await self._get_devices()
  File "/usr/local/lib/python3.8/site-packages/pyhs3ng/hometroller.py", line 158, in _get_devices
    d._set_root(self.all_devices[d.associated_devices[0]])
KeyError: 708
```

Reverted back to 1.0.4, and issue is gone. 

Let me know if I can provide any additional info

**Comment by anacozero** [comment]
Error seems to be reproduceable at version 1.0.4 if I change the pyhs3ng module version past 1.0.1 in the manifest.

**Comment by anacozero** [comment]
Issue seems to be due to some orphaned devices in Homeseer.  Some devices that are deleted are still showing up in `/JSON?request=getstatus` and are pointing to associated device "708" which does not exist at all anymore. So script fails at that point. 

Trying to figure out how to delete them currently and error should go away...

**Comment by anacozero** [comment]
Error is gone once all orphaned devices deleted in homeseer. Addon started up and I see all devices.

Not sure if this type of issue is easily circumvented with a try-except... My homeseer install may be a special case for this type of issue as it was littered with add-ons before I moved to home assistant.
